import { createHash } from "node:crypto";

/**
 * Markers for files sdd generates outside its own state (AGENTS.md, host agent
 * stubs, protocol). The marker carries a sha256 of the generated body, so sdd
 * can tell three cases apart:
 *
 * - `unmodified`: sdd wrote it and nobody changed it. Safe to regenerate or remove.
 * - `edited`: sdd wrote it, then someone edited it. Never overwrite or delete.
 * - `not-generated`: no marker (a user's own file, another tool's, or an old sdd
 *   version's). Never overwrite or delete.
 */
export type GeneratedState = "unmodified" | "edited" | "not-generated";

// Trailing spaces/tabs after `-->` and CRLF line endings are tolerated.
const MARKER_RE = /^<!-- sdd:generated sha256=([0-9a-f]{64})\b[^\n]*-->[ \t]*\r?\n/m;

/** Line endings are normalized (CRLF → LF) so a Windows/autocrlf checkout is not "edited". */
export function contentHash(body: string): string {
  return createHash("sha256").update(body.replace(/\r\n/g, "\n"), "utf8").digest("hex");
}

function markerLine(hash: string): string {
  return `<!-- sdd:generated sha256=${hash} (sdd regenerates this file only while it is unchanged; edit freely) -->\n`;
}

/** Insert the marker after YAML front matter (agent hosts parse it) or at the top. */
export function markGenerated(body: string): string {
  const line = markerLine(contentHash(body));
  if (body.startsWith("---\n")) {
    const close = body.indexOf("\n---\n", 3);
    if (close !== -1) {
      const at = close + "\n---\n".length;
      return body.slice(0, at) + line + body.slice(at);
    }
  }
  return line + body;
}

export function generatedState(content: string): GeneratedState {
  const m = MARKER_RE.exec(content);
  if (!m) return "not-generated";
  const body = content.slice(0, m.index) + content.slice(m.index + m[0].length);
  return contentHash(body) === m[1] ? "unmodified" : "edited";
}

/**
 * Why a file was left alone:
 * - `not-generated` / `edited`: see {@link GeneratedState}
 * - `symlink`: a symbolic link (or a path through one); sdd never follows, writes
 *   through, or deletes through links
 * - `unreadable`: could not be read, so sdd cannot prove it generated it
 */
export type KeptReason = "not-generated" | "edited" | "symlink" | "unreadable";

export interface KeptFile {
  /** Project-relative path */
  path: string;
  reason: KeptReason;
}

export function describeKept(k: KeptFile): string {
  switch (k.reason) {
    case "edited":
      return `${k.path} (generated by sdd, then edited — kept)`;
    case "symlink":
      return `${k.path} (symbolic link — not followed, left untouched)`;
    case "unreadable":
      return `${k.path} (could not be read — left untouched)`;
    default:
      return `${k.path} (not generated by sdd — left untouched)`;
  }
}
